version: '3.8'
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    env_file: .env
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
  web:
    build: ./project
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
  celery:
    build: ./project
    command: celery -A core worker -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file: .env
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./project
    command: celery -A core beat -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file: .env
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
